Rc 10
Red-Sock/Red-Cart pull request #4
Opened 2023-10-15 17:33 UTC by he1per30

2023-10-16 06:38 UTC, AlexSkilled commented
го будем называть ПРы так же как коммиты "[RC-10] Ручка создания корзины"

2023-10-16 06:47 UTC, AlexSkilled requested changes

2023-10-16 06:47 UTC, AlexSkilled commented on internal/data/inmemory/carts/carts.go
> +
оооо, вот это отлично. Теперь если два пользователя одновременно захотят создать корзину, мы получим гонку данных

плюс, в таком виде нумерация начнётся с 0, а данные мы начинаем хранить с 1 (типа 0 это пустое, значение по умолчанию, и когда ты возвращаешь пользаку 0 - не понятно, это оно не создалось или это оно создалось с значением 0)

2023-10-16 06:47 UTC, AlexSkilled commented on internal/data/inmemory/carts/carts.go
> +
заменить на работу через пакет atomic

2023-10-16 06:47 UTC, AlexSkilled commented on internal/data/inmemory/data.go
> +	return &Storage{Users: users.NewUsers(),
го по строчкам разнесём
```suggestion
	return &Storage{
	Users: users.NewUsers(),
```

2023-10-16 06:47 UTC, AlexSkilled commented on internal/data/inmemory/data.go
> +type Carts struct {
забыл убрать видимо

2023-10-16 06:47 UTC, AlexSkilled commented on internal/data/inmemory/users/users.go
> +	u.m[user.Id] = user
кстати! тут то тоже гонка данных за доступ к карте. Давай мьютексом покроем. Каким - подумай

2023-10-16 06:47 UTC, AlexSkilled commented on internal/interfaces/data/carts.go
> +	Get(ctx context.Context, id int64) (cart.Cart, error)
а в чём отличие? между методами

2023-10-16 06:47 UTC, AlexSkilled commented on internal/service/cart/cart.go
> +const msgString = "Корзина c id = %d была успешно создана. Друзья могут добавить корзину через /add_item %d имя_товара_1 имя_товара_2"
сейчас оно в одну строку, это не очень удобно. Чтобы не конкатенировать давай использовать символ обратной ковычки ` и разнесём на 3 строки "корзина... создана.", "Друзья...через" и на последней строчке команда

2023-10-16 06:47 UTC, AlexSkilled commented on internal/service/cart/cart.go
> +func (c CartsService) Create(ctx context.Context, idOwner int64) (error, string) {
ошибку всегда в конце передаём, это как с контекстом который передаём первым аргументом

2023-10-16 16:58 UTC, he1per30 commented on internal/interfaces/data/carts.go
> +	Get(ctx context.Context, id int64) (cart.Cart, error)
Show для будущей задачи RC-11, ее сигнатура исправится в рамках другой задачи, а сюда случайно попала)

2023-10-17 08:41 UTC, AlexSkilled requested changes

2023-10-17 08:41 UTC, AlexSkilled commented on internal/data/inmemory/carts/carts.go
> +		msg := fmt.Sprintf("У вас уже есть корзина с идентификатором = %d", cart.Id)
да

2023-10-17 08:41 UTC, AlexSkilled commented on internal/data/inmemory/carts/carts.go
> +	atomic.AddInt64(&idCart, 1)
в целом да, но лучше будет использовать atomic.Int64 

Сейчас мы в паре мест ограничиваем доступ к глобальной переменной. 

Лучше. Переменную с не потокобезопасным типом int заменить на потокобезопасную atomic.Int64 и уже не будет вариантов обосраться с ней. И давай её из пространства пакета перенесём в структуру. Она за пределами структуры всё равно не нужна

2023-10-17 08:41 UTC, AlexSkilled commented on internal/data/inmemory/carts/carts.go
> +	return idCart, nil
карта всё ещё не потоко безопасна, есть вариант при котором ты одновременно будешь в карту писать из N потоков. В результате это приведёт к панике. 

Без нагрузки это сложно отловить, потому что код будет потоково обрабатываться, но при малейшем скачке нагрузки получим две записи в карту и панику.



оберни использование карты мьютексами. Я вроде писал уже

2023-10-17 08:41 UTC, AlexSkilled commented on internal/data/inmemory/carts/carts.go
> +	panic("implement me")
давай паники заменим на возврат пустого значения и ошибки "not implemented"

2023-10-17 08:41 UTC, AlexSkilled commented on internal/data/inmemory/users/users.go
> +	u.m[user.Id] = user
тут сделал, а в другом репозитории нет

2023-10-17 08:41 UTC, AlexSkilled commented on internal/data/inmemory/users/users.go
> +	return u.m[id], nil
а что будет если мы одновременно с чтением будем записывать ?

2023-10-17 08:41 UTC, AlexSkilled commented on internal/service/cart/cart.go
> +
хорошо взять в привычку такую штуку как обёртка ошибок. Обычно у крупных компаний есть свои решения для оборачивания ошибок/логгирования и трейсинга.

У RedSock кстати тоже есть решение для оборачивания ошибок - https://github.com/Red-Sock/trace-errors воспользуйся

2023-10-18 05:30 UTC, he1per30 commented on internal/data/inmemory/carts/carts.go
> +	atomic.AddInt64(&idCart, 1)
Тогда вопрос, как мы инкрементировать на +1 каждый раз, если она у нас будет в структуре объявляться? Она же каждый раз будет иметь нулевое значение или я не о том думаю

2023-10-18 05:40 UTC, he1per30 commented on internal/data/inmemory/users/users.go
> +	return u.m[id], nil
Ну мы же покрыли RW мьютексами, можем спокойно читать и записывать у нас тут же не обновляются данные по пользователю он либо есть либо нет

2023-10-19 07:36 UTC, AlexSkilled commented on internal/data/inmemory/carts/carts.go
> +	atomic.AddInt64(&idCart, 1)
не о том думаешь. Во первых. Давай метод будет не к копии, а к экземпляру. Во вторых. atomic.Int64 - должен один раз инициализироваться и всё дальнейшее общение с ним должно идти напрямую

2023-10-19 07:38 UTC, AlexSkilled commented on internal/data/inmemory/carts/carts.go
> +	atomic.AddInt64(&idCart, 1)
У тебя пока не сформировалось понимание того как работать с объектами. Текущий вариант выглядит так 
<img width="356" alt="image" src="https://github.com/Red-Sock/Red-Cart/assets/48599701/084a519c-f4d9-4f77-8d2d-522fb242d9cd">


Есть объект. Вызывая вот этот метод Create мы **копируем** этот объект (Cart)

Что это значит? Что в памяти появляется 2й такой же объект У которого есть поле atomic.Int64 (не помню чо там внутри, считаем что это просто int64 переменная) 

Когда у этой переменной мы меняем значение через Add(1) мы меняем его у скопированной копии

2023-10-19 07:41 UTC, AlexSkilled commented on internal/data/inmemory/carts/carts.go
> +	atomic.AddInt64(&idCart, 1)
Решения два 

Первое
<img width="417" alt="image" src="https://github.com/Red-Sock/Red-Cart/assets/48599701/cee7907d-612c-4498-a967-8b28b3b4ba79">

В структуре хранить не объект, а ссылку на объект.

Что это значит? что ты где-то в памяти создал atomic.Int64 и в структуру Cart сохранил указатель на вот этот конкретный объект

Когда ты будешь вызывать Create ты всё ещё будешь копировать структуру Cart, НО в скопированной структуру будет лежать всё тот же **указатель** на уже созданный объект, а значит при работе с _inc_ ты будешь работать с одним и тем же объектом

2023-10-19 07:42 UTC, AlexSkilled commented on internal/data/inmemory/carts/carts.go
> +	atomic.AddInt64(&idCart, 1)
Второе
<img width="305" alt="image" src="https://github.com/Red-Sock/Red-Cart/assets/48599701/190296c0-c905-4028-b290-755c85871a96">

Метод будет привязан не к копии, а к указателю. Это значит, что при обращении к Create объект Cart не будет копироваться, а метод будет всегда работать с одной и той же структурой => с одними и теми же полями структуры

2023-10-19 07:59 UTC, AlexSkilled commented on internal/data/inmemory/carts/carts.go
> +	atomic.AddInt64(&idCart, 1)
![pointer drawio](https://github.com/Red-Sock/Red-Cart/assets/48599701/feee9406-f55e-4155-9b4f-adade85893c9)

2023-10-19 07:59 UTC, AlexSkilled commented on internal/data/inmemory/users/users.go
> +	return u.m[id], nil
<img width="694" alt="image" src="https://github.com/Red-Sock/Red-Cart/assets/48599701/b4acd1cf-b2a2-49cc-8ebf-6468e06afc20">
где покрыли то?

2023-10-19 08:00 UTC, AlexSkilled commented on internal/data/inmemory/users/users.go
> +	return u.m[id], nil
```suggestion
u.rw.RLock()
defer u.rw.RUnlock()
		return u.m[id], nil
```

2023-10-19 08:04 UTC, AlexSkilled commented on internal/data/inmemory/users/users.go
> +	return u.m[id], nil
"покрыть" - значит использовать.

Сейчас при вызове Create у тебя в методе мьютекс вызовется и если чо, второй паралелльный вызов Create заблокается.

Но если ты вызовешь Create (он запустился, залочил мьютекс) и вместе с ним вызовется Get (который знать не знает про мьютексы) то Get будет паралелльно записи из Create читать из карты.

2023-10-20 18:32 UTC, AlexSkilled requested changes

2023-10-20 18:32 UTC, AlexSkilled commented on internal/data/inmemory/carts/carts.go
>  func New() *Carts {
и чо, нормально пишется без инициализированной карты?

2023-10-20 18:32 UTC, AlexSkilled commented on internal/data/inmemory/carts/carts.go
>  	return c.m[idOwner], nil
опять чтение вне лока. Не делай мозги и сделай через дефер в начале

2023-10-20 18:32 UTC, AlexSkilled commented on internal/data/inmemory/carts/carts.go
>  	return idCatNew, nil
я дивлюсь, а тут ты решил через дефер, хотя мог через 

давай ка мы всё в одном стиле писать будем, через дефер. Да оно на краполюсичку медленне, но мы уверены что при выходе из функции оно выполнится (даже если панику словишь - а тут ты ловишь панику из за неициализированной карты)

2023-10-20 18:43 UTC, AlexSkilled commented on internal/data/inmemory/carts/carts.go
>  func New() *Carts {
нормально, гит не показал при ревью

2023-10-20 18:44 UTC, AlexSkilled commented on internal/data/inmemory/carts/carts.go
>  	return idCatNew, nil
панику не словишь, через дефер - делай

2023-10-20 18:47 UTC, he1per30 commented on internal/data/inmemory/carts/carts.go
>  	return idCatNew, nil
А вот и не словлю!)

2023-10-21 04:38 UTC, AlexSkilled approved these changes

2023-10-21 04:38 UTC, AlexSkilled commented on internal/data/inmemory/carts/carts.go
> +		return c.m[idOwner], errors.New(msg)
В будущем МРе подправишь
```suggestion
	cart, ok := c.m[idOwner]
	if ok {
		msg := fmt.Sprintf("У вас уже есть корзина с идентификатором = %d", cart.Id)
		return c.m[idOwner], errors.New(msg)
```

2023-10-21 04:38 UTC, AlexSkilled commented on internal/data/inmemory/carts/carts.go
> +		Url:     "",
```suggestion
	defer c.rw.Unlock()
	
	c.m[idOwner] = cart.Cart{
		Id:      idCatNew,
		OwnerId: idOwner,
		Url:     "",
```

2023-10-21 04:38 UTC, AlexSkilled commented on internal/service/user/user.go
>  		return "", err
```suggestion
	err = u.userData.Upsert(ctx, user)
	if err != nil {
		return "", err
```

2023-10-21 04:38 UTC, merged