Rc 11
Red-Sock/Red-Cart pull request #5
Opened 2023-10-25 06:29 UTC by he1per30

2023-10-25 19:54 UTC, AlexSkilled requested changes

2023-10-25 19:54 UTC, AlexSkilled commented on internal/data/inmemory/carts/cartItem.go
во, добавлю в доку по гошному стилю. Файлы именуем в змеином_футляре (snake case)

2023-10-25 19:54 UTC, AlexSkilled commented on internal/data/inmemory/carts/carts.go
> +	return idCartNew, nil
а ещё можно чуть круче сделать и писать сразу в поле корзины

```	
	newCart := &cart.Cart{
		OwnerId: idOwner,
	}	
	
	newCart.Id = c.idCart.Add(1)

	c.rw.Lock()
	defer c.rw.Unlock()

	c.idCartMap[idCartNew] = newCart
	c.ownerMap[idOwner] = newCart

	return idCartNew, nil

```

2023-10-25 19:54 UTC, AlexSkilled commented on internal/data/inmemory/carts/carts.go
> +	return idCartNew, nil
+ не забываем про визуально деление: вызовы rw должны быть отдельно, запись в карту отдельно, инициализация новой корзины отдельно

*отдельно - в смысле через пустые строки. Рассматривай вариант выше как пример

2023-10-25 19:54 UTC, AlexSkilled commented on internal/data/inmemory/carts/carts.go
> +	//TODO Чет я уже забыл где я это буду использовать, но обязательно буду!)
ну-ну

2023-10-25 19:54 UTC, AlexSkilled commented on internal/domain/cart/cartItem.go
> +	Items  []string
Items -> ItemNames

2023-10-25 19:54 UTC, AlexSkilled commented on internal/service/cart/cart.go
>  	id, err := c.cartsData.Create(ctx, idOwner)
а ежели `err != nil` что произойдёт?

2023-10-25 19:54 UTC, AlexSkilled commented on internal/service/cart/cart.go
>  	id, err := c.cartsData.Create(ctx, idOwner)
хорошенько подумай, тут у тебя лишнее 1 условие и 1 блока с if не хватает

2023-10-25 19:54 UTC, AlexSkilled commented on internal/service/cart/cart.go
> +func (c CartsService) GetByCartId(ctx context.Context, cartId int64) (cart.Cart, error) {
а чо мы всегда к указателю сервиса/репозитория обращались, а сейчас вдруг к значению?

2023-10-25 19:54 UTC, AlexSkilled commented on internal/service/cart/cart.go
> +func (c CartsService) GetByCartId(ctx context.Context, cartId int64) (cart.Cart, error) {
можно пояснить с аргументацией и оставить

2023-10-25 19:54 UTC, AlexSkilled commented on internal/service/service.go
>  func New(sD data.Storage) *Storage {
сервис для связи корзин-итемов добавился, а вот в конструктор его не добавили

2023-10-25 19:54 UTC, AlexSkilled commented on internal/service/service.go
>  func New(sD data.Storage) *Storage {
к слову нам сервис CartItem вовсе не нужен.

Концептуально, работа с товарами в корзине - это работа с корзиной => функционал который у тебя в CartItemService должен переехать в CartService

2023-10-25 19:54 UTC, AlexSkilled commented on internal/service/service.go
>  func New(sD data.Storage) *Storage {
вообще это не правильно, и дикие баяны бубуяны скажут "интерфейсы должны быть тонкими" (по солид) и вообще лучше не сервисы использовать, а ещё один слой - юзкейсов, и в нём обращаться в два других слоя- данные и функции над объектами (аля калькулятор) **но мне как-то похуй** на ебалоидов теоретиков, пускай сидят книжки свои по чистому программированию дрочат и потом в 50 местах один и тот же интерфейс меняют.

Двигаем функционал из ItemCartService в CartService и не забиваем голову хернёй

2023-10-25 19:54 UTC, AlexSkilled commented on internal/transport/telegram/handlers/cart/add/addHandler.go
> +	return "add Item"
Adds item to cart хотя бы

2023-10-25 19:54 UTC, AlexSkilled commented on internal/transport/telegram/handlers/cart/add/addHandler.go
> +	}
можно заменить на простой if с условием. У тебя же тут какое условие. Если аргументов 1 или 2 (т.е меньше 3х) - покажи сообщение и выйди

2023-10-25 19:54 UTC, AlexSkilled commented on internal/transport/telegram/handlers/cart/add/addHandler.go
> +}
да не, какой дубль кода, ты просто "переписал" (а точнее обернул) Atoi и сделал вместо err   возращяемое значение - bool

есть две опции:

1. по логике, корзина не может иметь идентификатор 0 - соответственно можем игнорить ошибку и если из strconv.Atoi вернулся ноль - выкидывать свою ошибку
2. тоже самое, только проверять на ошибку

первый варик смотрится как то что надо

2023-10-25 19:54 UTC, AlexSkilled commented on internal/transport/telegram/handlers/cart/add/addHandler.go
> +}
ну это потом уедет в сервис корзины (по крайней мере делать ему тут нечего)

2023-10-26 16:39 UTC, he1per30 commented on internal/service/cart/cart.go
> +func (c CartsService) GetByCartId(ctx context.Context, cartId int64) (cart.Cart, error) {
Поправил на указатель, но не знаю в каких случаях это лучше

2023-10-27 18:29 UTC, he1per30 commented on internal/service/service.go
>  func New(sD data.Storage) *Storage {
Функционал подвинул, надеюсь я так тебя понял)

2023-10-27 18:37 UTC, he1per30 commented on internal/transport/telegram/handlers/cart/add/addHandler.go
> +}
Ты имеешь ввиду, что GetByCartId должен сразу будет возвращать какую то строку с информацией?

2023-10-27 20:42 UTC, AlexSkilled commented on internal/transport/telegram/handlers/cart/add/addHandler.go
> +}
нет, имею ввиду что это ( выделенный кусок, за исключением out ) уйдёт на уровень работы корзины

2023-10-27 20:43 UTC, AlexSkilled commented
названия для МРов давай подробнее называть - [RC-11]: команда добавления в корзину

2023-10-27 20:56 UTC, AlexSkilled requested changes

2023-10-27 20:56 UTC, AlexSkilled commented on internal/data/inmemory/carts/cart_item.go
> +func (c *CartItem) CreateCartsItem(ctx context.Context, cartId int64) (id int64, err error) {
Тудушку сюда или реализация метода ещё будет?

2023-10-27 20:56 UTC, AlexSkilled commented on internal/data/inmemory/carts/carts.go
>  	defer c.rw.RUnlock()
Логическое отделение блоков 


```suggestion
	c.rw.RLock()
	defer c.rw.RUnlock()
	
	cartNew, ok := c.idCartMap[cartId]
```

2023-10-27 20:56 UTC, AlexSkilled commented on internal/data/inmemory/carts/carts.go
> +	return newCart.Id, nil
с этим методом всё хорошо, жду когда остальные будут такими 
же

2023-10-27 20:56 UTC, AlexSkilled commented on internal/data/inmemory/carts/carts.go
> +	return newCart.Id, nil
а ну раз уж выше мы в OwnerId пишем, то можно так же писать и Id 

```
newCart := &cart.Cart{
		OwnerId: idOwner,
CartId: c.idCart.Add(1),
	}
```

2023-10-27 20:56 UTC, AlexSkilled commented on internal/interfaces/data/cart_item.go
> +}
не, чото ты не всёк что я хотел. 

Логика какая, Мы хотим **добавить** в **корзину** **продукты**

Значит метод который ты подаразумеваешь тут, должен уехать в репозиторий корзины

2023-10-27 20:56 UTC, AlexSkilled commented on internal/service/cart/cart.go
> +
ваще нихуя не понимаю что тут происходит

2023-10-27 20:56 UTC, AlexSkilled commented on internal/service/cart/cart.go
>  }
хуета какая-то.

файл сервиса:

Структура сервиса
Конструктор структуры выше
Методы структуры.


на хер нам тут две структуры, одна в другой, конструктор сверху

2023-10-27 20:56 UTC, AlexSkilled commented on internal/service/service.go
>  func New(sD data.Storage) *Storage {
и не передвинул нихера в итоге

2023-10-27 20:56 UTC, AlexSkilled commented on internal/transport/telegram/handlers/cart/add/addHandler.go
> +	id, _ := strconv.Atoi(commandFromTg[1]) //checkIdForInteger(commandFromTg[1])
чо за мёртвый коммент

2023-10-28 20:03 UTC, he1per30 commented on internal/data/inmemory/carts/carts.go
>  	defer c.rw.RUnlock()
А что тут конкретно не отделено? Мьютексы идут рядом друг с другом. Добавление в мапы отдельно.

2023-10-28 20:04 UTC, he1per30 commented on internal/data/inmemory/carts/carts.go
>  	defer c.rw.RUnlock()
Ты ниже сказал, что все ок с методом)

2023-10-28 20:07 UTC, he1per30 commented on internal/service/cart/cart.go
> +
"Двигаем функционал из ItemCartService в CartService и не забиваем голову хернёй". Подвинул) Но кажется я не так понимаю слово подвинуть) Как тогда еще можно передвинуть эту фигню)

2023-10-28 20:07 UTC, he1per30 commented on internal/service/cart/cart.go
>  }
Ну и из фигни выше по той же логике переносил)

2023-10-28 20:07 UTC, he1per30 commented on internal/transport/telegram/handlers/cart/add/addHandler.go
> +	id, _ := strconv.Atoi(commandFromTg[1]) //checkIdForInteger(commandFromTg[1])
Сорри, проглядел

2023-10-30 10:28 UTC, AlexSkilled requested changes

2023-10-30 10:28 UTC, AlexSkilled commented on internal/data/inmemory/carts/carts.go
>  	defer c.rw.RUnlock()
бля ёпта, в смысле отдельно? мьютекс на 32 строке закрывается, чтение из карты на 33. Где строка между ними?

2023-10-30 10:28 UTC, AlexSkilled commented on internal/data/inmemory/carts/carts.go
> +	}
аналогично, мьютексы слеплены с чтением

2023-10-30 10:28 UTC, AlexSkilled commented on internal/data/inmemory/carts/carts.go
> +func (c *Carts) AddCartItems(ctx context.Context, items []string, cardId int64, userId int64) error {
нуу, хз, по сигнатуре функции, а если мы ещё какие-то поля захотим добавить? а если 10 полей в итоге будет у сущности CartItem?

2023-10-30 10:28 UTC, AlexSkilled commented on internal/data/inmemory/carts/carts.go
> +	c.ShowCart(ctx, cardId)
чо за функция, чо проверяет, хер пойми

2023-10-30 10:28 UTC, AlexSkilled commented on internal/data/inmemory/carts/carts.go
> +		fmt.Println(items)
ну тогда уж ListItems какой-нибудь.

принт в консоль убери. Если очень сильно хочешь, то сделай через `_ = items`, но вообще, сейчас мешанина из хуйни получается, задача про добавление в корзину, а мы зачем-то ещё и функцию для показа делаем

2023-10-30 10:28 UTC, AlexSkilled commented on internal/data/inmemory/data.go
> +	cartItem *cart.CartItem
зачем нам тут `cartItem *cart.CartItem` вроде в *carts.Carts вынесли

2023-10-30 10:28 UTC, AlexSkilled commented on internal/interfaces/data/carts.go
> +	GetByCartId(ctx context.Context, id int64) (cart.Cart, error)
читаем что пишем

сервис "работы с корзинами"
- метод "получить по id владельца" ✅️
- метод "получить по id _корзины_"🔴
- метод "добавить корзинные товары" 🟨

лучше избегать в методах названия интерфейса. 

Т.е при получении по ID мы понимаем, что мы получаем по ID основной сущности

Так же при добавлении товаров. Понятно что мы добавляем Товары для корзины, поэтому можно просто AddItem

Хороший пример в данном случае первый метод (который ты не трогал и хорошо) - Create - "Создай". Так как он находится в интерфейсе "Корзина" мы понимаем, что "Создай" означает "Создай корзину"

2023-10-30 10:28 UTC, AlexSkilled commented on internal/service/cart/cart.go
> +
функционал = функции которые ты написал для CartItemService.

Двигать = удаляешь CartItemService структуру и функции которые ты писал для неё, переносишь в CartService

Суть же в чём:
CartItemService - сервис занимающийся товарами в корзине. Как по мне - много чести этим товарам в корзине, чтоб для них отдельный интерфейс задавать. Логики с ними нет никакой, он просто держат данные и являются составной частью корзины. Без привязки к корзине они смысла не имеют.

2023-10-30 10:28 UTC, AlexSkilled commented on internal/service/cart/cart.go
>  }
дропай структуру CartItemService и всё что с ней связано (её функции) переноси в CartService

2023-10-30 10:28 UTC, AlexSkilled commented on internal/service/cart/cart.go
> +
непонел

2023-10-30 10:28 UTC, AlexSkilled commented on internal/service/cart/cart.go
> +
ну ошибка и ошибка, обработали, отправили, в чём разница? тебе вообще тут про реализацию думать не нужно. 

У тебя есть интерфейс с методом - получить корзину по владельцу. Она возвращает корзину или ошибку. Вернула ошибку - выкинь ошибку выше, вернула корзину - работаем дальше.

Суть как раз в том чтобы ты не думал чо там внутри этого метода и сокращал область в рамках которой думаешь до вот этого метода

2023-10-30 10:28 UTC, AlexSkilled commented on internal/service/cart/cart.go
> +	}
да не, а нафиг тебе лишняя абстракция 

сейчас:
- вызов метода AddCartItems
- вызов метода GetByCartId
    - вызов метода GetByCartId у слоя с данными

вот этот 2й пункт можно опустить, он тебе не нужен

2023-10-30 10:28 UTC, AlexSkilled commented on internal/service/cart/cart.go
> +		return cart, err
хз, спорный момент, можем сейчас оставить, но тогда везде потом будем делать так.

Отойдя от текущего метода:
По сути при получении чего-то из метода мы получаем что-то либо ошибку. то есть ЛИБО структуру, ЛИБО ошибку

Исключения: сложный процесс сборки данных, в ходе которых может что-то произойти и часть данных не соберётся. Тогда мы возвращаем и данные и ошибку

+ на такой случай нужно определённые ошибки на уровне работы с данными заводить и потом отлавливать эти ошибки при использовании

ЧО ИМЕЮ ВВИДУ

есть слой с данными: там есть метод получи всю информацию по пользователю, для этого нужно сходить в 10 микросервисов.

Заводим 10 ошибок на уровне пакета (аля "не удалось получить аватар", "не удалось получить био")

Делаем запросы в 10 сервисов за доп инфой для пользака

Если отработало 4 запроса и на 5й чото сломалось (микросервис сломался, откис запрос) - мы не сразу выходим и выдаём ошибку, а просто пишем ошибку в какой-нибудь срез и идём дальше.

Вот так мы собрали со всех сервисов инфу которую смогли. Собрали "портрет" пользака (например) и вернули инфу + ошибки

Там где этот метод вызывался проверяем "есть ошибка ?" если нет -работаем как надо, Если есть - проверяем какая это ошибка. 

Допустим для нас критично получить ФИО, БИО и ещё какую-нибудь инфу, а вот Аватар нам не усрался. Видим что среди ошибок только 1 ошибка - получения аватара - тогда похер на ошибку и идём дальше


В общем, вопрос сложный вот такой подход, который я выше описал мне кажется приемлемым, во всех остальных случаях лучше вернуть пустую структуру cart.Cart{} вместо cart который получился в результате вызова метода GetByCartId

2023-10-30 10:28 UTC, AlexSkilled commented on internal/service/cart/cart.go
> +		return cart, err
к слову, тут обсёр в плане нейминга: cart - имя импортируемого пакета, cart - результат вызова c.cartsData.GetByCartId(ctx, cartId)

давай переименуем. Метод маленький, приемлем вариант названия "res"

Если бы у нас там ниже ещё 20 строк логики применялись, тогда надо было бы подумать. cartRes, **cartData**

2023-10-30 10:28 UTC, AlexSkilled commented on internal/service/cart/cart.go
> +	cart, err := c.cartsData.GetByOwnerId(ctx, idOwner)
та же хуйня

2023-10-30 10:28 UTC, AlexSkilled commented on internal/transport/telegram/handlers/cart/add/addHandler.go
> +	outMsg = "Предметы были успешно добавлены в корзину!"
а чо зачем его в переменную писать, го сразу в метод строку передавать

2023-10-30 13:44 UTC, he1per30 commented on internal/data/inmemory/carts/carts.go
>  	defer c.rw.RUnlock()
Ц, я не увидел Suggested change. Думал что ну вот же оно отделено) Поправил в коде

2023-10-30 16:34 UTC, he1per30 commented on internal/data/inmemory/carts/carts.go
> +	c.ShowCart(ctx, cardId)
Пока что заглушка, в дальнейшей реализации ее не будет

2023-10-30 21:49 UTC, AlexSkilled requested changes
хуйня какая-та, почему я до сих пор вижу CartItem не только как структуру для данных

2023-10-30 21:49 UTC, AlexSkilled commented on internal/data/inmemory/carts/carts.go
> +
лишняя строка (починить и можно мёржить)

2023-10-30 21:49 UTC, AlexSkilled commented on internal/data/inmemory/carts/carts.go
> +	c.ShowCart(ctx, cardId)
ок

2023-10-30 21:49 UTC, AlexSkilled commented on internal/data/inmemory/data.go
> +	cartItem *cart.CartItem
опять же от cartItem надо избавиться

2023-10-30 21:49 UTC, AlexSkilled commented on internal/service/cart/cart.go
> +		cartItem:  NewCartItem(),
я конечно пьяный, но всё ещё не вдупляю нах тут cartitem

2023-10-30 21:49 UTC, AlexSkilled commented on internal/service/cart/cart.go
> +		msg := fmt.Sprintf("Ошибка БД при получения корзины по Id")
тож хуйня, сразу в метод ниже передай

2023-10-30 21:49 UTC, AlexSkilled commented on internal/service/cart/cart.go
> +		return "", errors.New(msg)
анал огично

2023-10-30 21:49 UTC, AlexSkilled commented on internal/service/cart/cart.go
> +		return errors.New(outMsg)
анал огично

2023-10-30 21:49 UTC, AlexSkilled commented on internal/service/cart/cart.go
> +	//TODO добавить логику с ошибкой и возвратом ответа, если он нужен
если TODO то в рамках какой задачи

2023-10-30 21:49 UTC, AlexSkilled commented on internal/service/cart/cart.go
> +		//TODO надеюсь я тебя правильно понял)
прально, удоляй

2023-10-30 21:49 UTC, AlexSkilled commented on internal/service/service.go
> +	CartItemService *cart.CartItemService
нахуй эту структуру надо

2023-10-30 21:49 UTC, AlexSkilled commented on internal/transport/telegram/handlers/cart/add/addHandler.go
> +}
получается сначала ошибку отправляем, потом сообщение об успешном добавлении

2023-10-31 12:16 UTC, AlexSkilled commented
заебёшь, когда ещё попросил МР переименовать

2023-10-31 12:19 UTC, AlexSkilled requested changes

2023-10-31 12:19 UTC, AlexSkilled commented on internal/data/inmemory/carts/carts.go
>  	}
по факту, кста (этого делать сейчас не надо, но на будущее) cartItem можно хранить прямо в Cart

2023-10-31 12:19 UTC, AlexSkilled commented on internal/data/inmemory/carts/carts.go
> +		return cart.Cart{}, errors.New("Корзина не найдена")
тут обсуждали, можем просто выкидывать пустую cart.Cart{} без ошибки

2023-11-02 18:23 UTC, AlexSkilled requested changes

2023-11-02 18:23 UTC, AlexSkilled commented on internal/interfaces/data/carts.go
> +	GetByCartId(ctx context.Context, id int64) (cart.Cart, error)
видимо непонятно объясняю и нужно просто сказать как делать?

2023-11-02 18:23 UTC, AlexSkilled commented on internal/service/cart/cart.go
> +
нахуй она тут нужна

2023-11-02 18:23 UTC, AlexSkilled commented on internal/transport/telegram/listener.go
> +		s.bot.AddCommandHandler(create.New(srv.Cart()))
го тут тоже разделим

```
s.bot.AddCommandHandler(version.New(cfg))
s.bot.AddCommandHandler(welcome.New(srv.User()))

s.bot.AddCommandHandler(add.New(srv.Cart()))
s.bot.AddCommandHandler(create.New(srv.Cart()))
```

2023-11-02 18:23 UTC, AlexSkilled commented on internal/data/inmemory/carts/carts.go
> +	cartNew, ok := c.ownerMap[ownerId]
а чо по неймингам

почему она cart**New** 

_result_ хотя бы

2023-11-02 18:23 UTC, AlexSkilled commented on internal/service/cart/cart.go
> +
нахуй оно тут надо

2023-11-02 18:23 UTC, AlexSkilled commented on internal/transport/telegram/handlers/cart/add/addHandler.go
> +	commandFromTg := strings.Split(in.Text, " ")
блин, вроде должно быть что-то типа in.Args в котором уже разделённые аргументы

2023-11-02 18:23 UTC, AlexSkilled commented on internal/transport/telegram/handlers/cart/add/addHandler.go
> +	commandFromTg := strings.Split(in.Text, " ")
если нет, то оставь

2023-11-02 19:30 UTC, AlexSkilled approved these changes
заебало уже этот мр смотреть, давай некст

2023-11-03 10:26 UTC, merged